name: Generate Resume PDF

on:
  push:
    paths:
      - resume/resume_template.tex

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up TeX Live
      uses: dante-ev/latex-action@v2
      with:
        root_file: resume/resume_template.tex

    - name: Compile LaTeX document
      run: latexmk -pdf -outdir=resume resume/resume_template.tex

    - name: Commit and push generated PDF
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add resume/resume_template.pdf
        git commit -m 'Generate resume_template.pdf'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

